# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "CTMartin-Photos"
license = "MIT"
licenselink = "https://github.com/ct-martin/photo-gallery/blob/master/themes/ctmartin/LICENSE"
description = ""
homepage = "https://github.com/ct-martin/photo-gallery/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "CTMartin"
  homepage = "https://ctmartin.dev/"
